-- Cloud Registration System
-- Run this whole file once in Supabase > SQL Editor.

create table if not exists public.people (
  no text primary key,
  first_name text not null default '',
  last_name text not null default '',
  birth_date text not null default '',
  id_number text not null default '',
  district text not null default '',
  office text not null default '',
  school text not null default '',
  supervisor text not null default '',
  assigned text not null default ''
);

create index if not exists people_id_number_upper_idx
  on public.people (upper(id_number));

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin','sender')),
  device_name text not null default '',
  active boolean not null default true
);

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  person_no text not null unique references public.people(no) on delete cascade,
  registered_at timestamptz not null default now(),
  sender_user_id uuid references auth.users(id),
  device_name text not null default ''
);

create index if not exists registrations_registered_at_idx
  on public.registrations (registered_at desc);

create table if not exists public.system_state (
  id integer primary key check (id = 1),
  reset_version bigint not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.system_state(id, reset_version)
values (1, 0)
on conflict (id) do nothing;

alter table public.people enable row level security;
alter table public.profiles enable row level security;
alter table public.registrations enable row level security;
alter table public.system_state enable row level security;

-- Helper used by policies and RPC functions.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where user_id = auth.uid()
      and role = 'admin'
      and active = true
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "profiles_self_or_admin_select" on public.profiles;
create policy "profiles_self_or_admin_select"
on public.profiles for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "admin_people_select" on public.people;
create policy "admin_people_select"
on public.people for select
to authenticated
using (public.is_admin());

drop policy if exists "admin_registrations_select" on public.registrations;
create policy "admin_registrations_select"
on public.registrations for select
to authenticated
using (public.is_admin());

drop policy if exists "admin_system_state_select" on public.system_state;
create policy "admin_system_state_select"
on public.system_state for select
to authenticated
using (public.is_admin());

grant select on public.profiles to authenticated;
grant select on public.people to authenticated;
grant select on public.registrations to authenticated;
grant select on public.system_state to authenticated;

-- Sender/Admin registration endpoint.
-- IMPORTANT: returns only status + submitted number; it never returns personal data.
create or replace function public.register_person(p_identifier text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_role text;
  v_device text;
  v_person_no text;
  v_inserted text;
begin
  if v_uid is null then
    raise exception 'Authentication required';
  end if;

  select role, device_name
    into v_role, v_device
  from public.profiles
  where user_id = v_uid
    and active = true;

  if v_role is null or v_role not in ('sender','admin') then
    raise exception 'Not authorized';
  end if;

  -- Priority 1: No
  select no into v_person_no
  from public.people
  where no = trim(p_identifier)
  limit 1;

  -- Priority 2: ID card
  if v_person_no is null then
    select no into v_person_no
    from public.people
    where upper(id_number) = upper(trim(p_identifier))
      and id_number <> ''
    limit 1;
  end if;

  if v_person_no is null then
    return jsonb_build_object(
      'status','invalid',
      'identifier',trim(p_identifier)
    );
  end if;

  insert into public.registrations(person_no, sender_user_id, device_name)
  values (v_person_no, v_uid, coalesce(v_device,''))
  on conflict (person_no) do nothing
  returning person_no into v_inserted;

  if v_inserted is null then
    return jsonb_build_object(
      'status','already',
      'identifier',trim(p_identifier)
    );
  end if;

  return jsonb_build_object(
    'status','registered',
    'identifier',trim(p_identifier)
  );
end;
$$;

revoke all on function public.register_person(text) from public;
grant execute on function public.register_person(text) to authenticated;

create or replace function public.reset_registrations()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin only';
  end if;

  delete from public.registrations;

  update public.system_state
     set reset_version = reset_version + 1,
         updated_at = now()
   where id = 1;

  return jsonb_build_object('status','reset');
end;
$$;

revoke all on function public.reset_registrations() from public;
grant execute on function public.reset_registrations() to authenticated;
